"""
build_submission_package.py — assemble the COR submission package from the
current paper/ sources into submission_package/.

This is a snapshot builder, not a source of truth: submission_package/ is
regenerated from paper/ each run and should be rebuilt (rerun this script)
any time paper/main.tex, paper/supplementary.tex, paper/refs.bib,
paper/highlights.txt, or paper/cover_letter.md change, right before the
actual submission.

Contents assembled, matched against the COR/Elsevier Guide for Authors
(live-verified 2026-08-30, https://www.sciencedirect.com/journal/computers-
and-operations-research/publish/guide-for-authors):
  manuscript/     main.tex, refs.bib, figures/*.pdf, main.pdf  (editable
                  LaTeX source + compiled PDF; source is what Elsevier
                  actually requires for typesetting, PDF is the reviewer-
                  facing copy)
  supplementary/  supplementary.tex, refs.bib, supplementary.pdf
  highlights.txt  required separate file, filename must contain "highlights"
  cover_letter.md optional courtesy, not a formal COR requirement
  README.md       manifest + remaining manual-action checklist

NOT included (must be done by the corresponding author, not automatable):
  - The signed competing-interest declaration .docx from
    https://declarations.elsevier.com/ (the in-manuscript section satisfies
    the article-text requirement; the online tool's document is a separate
    upload the corresponding author must generate personally).
  - Confirming the GitHub repository is actually public before upload.
  - Final reviewer-suggestion names, if the optional courtesy section in the
    cover letter is to be completed rather than left as-is or removed.

Usage:
    python build_submission_package.py
"""
import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
PAPER = os.path.join(ROOT, "paper")
OUT = os.path.join(ROOT, "submission_package")

README = """# COR submission package

Snapshot generated by `build_submission_package.py` from `paper/` — rebuild
this folder (rerun the script) after any further edit to the manuscript,
supplement, highlights, or cover letter, right before actual submission.

## Contents

| Item | Path | COR/Elsevier requirement |
| --- | --- | --- |
| Manuscript LaTeX source | `manuscript/main.tex`, `manuscript/refs.bib`, `manuscript/figures/` | Required: editable source files (.tex, not PDF alone) |
| Manuscript compiled PDF | `manuscript/main.pdf` | Reviewer-facing copy; system also auto-converts source to PDF |
| Supplementary material | `supplementary/supplementary.tex`, `supplementary/refs.bib`, `supplementary/supplementary.pdf` | Required if referenced from the main text (it is) |
| Highlights | `highlights.txt` | Required: 3-5 bullets, <=85 chars each, filename must contain "highlights" |
| Cover letter | `cover_letter.md`, `cover_letter.pdf` | Optional courtesy; `.pdf` is the actual upload format (portal does not accept `.md`) |
| Competing-interest/funding text for the declarations tool | `competing_interest_declaration_tool_text.txt` | Reference text to paste into declarations.elsevier.com; does not replace using the tool itself |

## In the manuscript already (no separate file needed)

- Declaration of competing interest (`\\section*{Declaration of competing interest}`)
- Declaration of generative AI and AI-assisted technologies (`\\section*{Declaration of generative AI...}`)
- CRediT authorship contribution statement
- Data and code availability statement

## Still required from the corresponding author before upload (not automatable)

1. **Signed competing-interest declaration document.** COR requires this be
   generated through Elsevier's own declarations tool
   (https://declarations.elsevier.com/), producing a `.doc`/`.docx` uploaded
   as a separate file at the "attach/upload files" submission step. The
   in-manuscript section above satisfies the article-text requirement but
   does not replace this separate signed document. The exact text to enter
   into the tool is prepared in `competing_interest_declaration_tool_text.txt`
   in this package — the tool itself still has to be used interactively.
2. **Confirm the GitHub repository is actually public** at the URL asserted
   in `manuscript/main.tex` (`Data and code availability`) before submitting.
3. **Suggested reviewers** in `cover_letter.md` are an optional courtesy with
   citation-grounded candidates already filled in; verify affiliation/email/
   conflict-of-interest if kept, or remove the section, or submit as-is.
4. **Graphical abstract** is encouraged, not required, and is not included
   here; add one only if desired.
5. Submit via the journal's online system: https://submit.elsevier.com/CAOR
"""


def _clean_dir(path):
    if os.path.isdir(path):
        for root, dirs, files in os.walk(path):
            for name in files:
                fp = os.path.join(root, name)
                try:
                    os.remove(fp)
                except PermissionError:
                    print(f"WARNING: could not remove (locked, likely open in a "
                          f"viewer) - leaving stale copy in place: {fp}")
    else:
        os.makedirs(path)


def _copy(src, dst):
    try:
        shutil.copy2(src, dst)
    except PermissionError:
        print(f"WARNING: could not overwrite (locked, likely open in a viewer) "
              f"- leaving stale copy in place: {dst}")


def main():
    _clean_dir(OUT)

    manuscript_dir = os.path.join(OUT, "manuscript")
    os.makedirs(manuscript_dir, exist_ok=True)
    for name in ("main.tex", "refs.bib", "main.pdf"):
        _copy(os.path.join(PAPER, name), os.path.join(manuscript_dir, name))
    figures_dir = os.path.join(manuscript_dir, "figures")
    os.makedirs(figures_dir, exist_ok=True)
    for name in os.listdir(os.path.join(PAPER, "figures")):
        _copy(os.path.join(PAPER, "figures", name), os.path.join(figures_dir, name))

    supp_dir = os.path.join(OUT, "supplementary")
    os.makedirs(supp_dir, exist_ok=True)
    for name in ("supplementary.tex", "refs.bib", "supplementary.pdf"):
        _copy(os.path.join(PAPER, name), os.path.join(supp_dir, name))

    _copy(os.path.join(PAPER, "highlights.txt"), os.path.join(OUT, "highlights.txt"))
    _copy(os.path.join(PAPER, "cover_letter.md"), os.path.join(OUT, "cover_letter.md"))
    _copy(os.path.join(PAPER, "competing_interest_declaration_tool_text.txt"),
          os.path.join(OUT, "competing_interest_declaration_tool_text.txt"))

    # Portal upload needs a real document format, not .md; regenerate it here
    # too so a rebuild never silently deletes it (build_cover_letter_pdf.py
    # writes straight into OUT).
    cover_letter_pdf_builder = os.path.join(ROOT, "build_cover_letter_pdf.py")
    if os.path.exists(cover_letter_pdf_builder):
        subprocess.run([sys.executable, cover_letter_pdf_builder], check=True)

    with open(os.path.join(OUT, "README.md"), "w", encoding="utf-8") as f:
        f.write(README)

    print(f"Wrote {OUT}")
    for dirpath, _, filenames in os.walk(OUT):
        for name in sorted(filenames):
            rel = os.path.relpath(os.path.join(dirpath, name), OUT)
            print(f"  {rel}")


if __name__ == "__main__":
    main()
